#!/bin/bash
#echo "Add your files to be compiled and linked here:"
#read files
echo "Compiling ...."
echo "_________________ Errors ________________"
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 ../*.c tmain.c -Wno-format -o test
echo " "
echo "___________ ./out to run ________________"
